------------------------------------------------------------------------
-----------------------Migration 8 — Returns & Reverse Logistics
------------------------------------------------------------------------
------------------------------------------------------------------------
----------------- trigger trg_validate_return_item_quantity
------------------------------------------------------------------------
CREATE TRIGGER trg_validate_return_item_quantity
BEFORE INSERT OR UPDATE OF
    quantity_requested,
    sales_order_item_id,
    sales_order_id,
    organization_id
ON returns.return_items
FOR EACH ROW
EXECUTE FUNCTION returns.validate_return_item_quantity();
------------------------------------------------------------------------
----------------- function returns.validate_return_item_quantity
-----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION returns.validate_return_item_quantity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_fulfilled_quantity INTEGER;
    v_reserved_quantity  INTEGER;
BEGIN
    -- Lock the original sales-order item so concurrent return requests
    -- cannot both reserve the same remaining quantity.
    SELECT soi.fulfilled_quantity
    INTO v_fulfilled_quantity
    FROM public.sales_order_items soi
    WHERE soi.sales_order_item_id = NEW.sales_order_item_id
      AND soi.sales_order_id = NEW.sales_order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Sales order item % was not found for sales order %',
            NEW.sales_order_item_id,
            NEW.sales_order_id;
    END IF;

    SELECT COALESCE(SUM(ri.quantity_requested), 0)
    INTO v_reserved_quantity
    FROM returns.return_items ri
    JOIN returns.returns r
      ON r.return_id = ri.return_id
     AND r.organization_id = ri.organization_id
    JOIN returns.return_statuses rs
      ON rs.return_status_id = r.return_status_id
    WHERE ri.organization_id = NEW.organization_id
      AND ri.sales_order_item_id = NEW.sales_order_item_id
      AND rs.status_code NOT IN ('rejected', 'cancelled')
      AND (
            TG_OP = 'INSERT'
            OR ri.return_item_id <> NEW.return_item_id
          );

    IF v_reserved_quantity + NEW.quantity_requested > v_fulfilled_quantity THEN
        RAISE EXCEPTION
            'Return quantity exceeds fulfilled quantity. Fulfilled: %, already reserved: %, requested: %, remaining: %',
            v_fulfilled_quantity,
            v_reserved_quantity,
            NEW.quantity_requested,
            v_fulfilled_quantity - v_reserved_quantity;
    END IF;

    RETURN NEW;
END;
$$;

------------------------------------------------------------------------
-----------------table returns.return_items
------------------------------------------------------------------------
CREATE TABLE returns.return_items (
    return_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id INTEGER NOT NULL,
    return_id BIGINT NOT NULL,

    sales_order_id INTEGER NOT NULL,
    sales_order_item_id INTEGER NOT NULL,

    variant_id INTEGER NOT NULL,
    return_reason_id INTEGER NOT NULL,

    quantity_requested INTEGER NOT NULL,
    quantity_approved INTEGER,
    quantity_received INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_return_items_org_return_item
        UNIQUE (organization_id, return_item_id),

    CONSTRAINT uq_return_items_return_sales_item
        UNIQUE (
            organization_id,
            return_id,
            sales_order_item_id
        ),

    CONSTRAINT fk_return_items_return
        FOREIGN KEY (
            organization_id,
            return_id
        )
        REFERENCES returns.returns (
            organization_id,
            return_id
        ),

    CONSTRAINT fk_return_items_sales_order_item
        FOREIGN KEY (
            sales_order_id,
            sales_order_item_id
        )
        REFERENCES public.sales_order_items (
            sales_order_id,
            sales_order_item_id
        ),

    CONSTRAINT fk_return_items_variant
        FOREIGN KEY (variant_id)
        REFERENCES public.product_variants (variant_id),

    CONSTRAINT fk_return_items_reason
        FOREIGN KEY (
            organization_id,
            return_reason_id
        )
        REFERENCES returns.return_reasons (
            organization_id,
            return_reason_id
        ),

    CONSTRAINT chk_return_items_quantity_requested
        CHECK (quantity_requested > 0),

    CONSTRAINT chk_return_items_quantity_approved
        CHECK (
            quantity_approved IS NULL
            OR (
                quantity_approved > 0
                AND quantity_approved <= quantity_requested
            )
        ),

    CONSTRAINT chk_return_items_quantity_received
        CHECK (
            quantity_received >= 0
        ),

    CONSTRAINT chk_return_items_received_not_above_approved
        CHECK (
            quantity_approved IS NULL
            OR quantity_received <= quantity_approved
        )
);

------------------------------------------------------------------------
----------------table returns.returns_reasons
------------------------------------------------------------------------
CREATE TABLE returns.return_reasons (
    return_reason_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id INTEGER NOT NULL,

    reason_code VARCHAR(50) NOT NULL,
    reason_name VARCHAR(100) NOT NULL,
    description TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_return_reasons_organization
        FOREIGN KEY (organization_id)
        REFERENCES public.organizations (organization_id),

    CONSTRAINT uq_return_reasons_org_code
        UNIQUE (organization_id, reason_code),

    CONSTRAINT uq_return_reasons_org_reason_id
        UNIQUE (organization_id, return_reason_id),

    CONSTRAINT chk_return_reasons_code_not_blank
        CHECK (btrim(reason_code) <> ''),

    CONSTRAINT chk_return_reasons_name_not_blank
        CHECK (btrim(reason_name) <> '')
);


------------------------------------------------------------------------
---------------table returns.returns
------------------------------------------------------------------------

CREATE TABLE returns.returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id INTEGER NOT NULL,
    return_number VARCHAR(50) NOT NULL,

    sales_order_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,

    return_status_id INTEGER NOT NULL,

    initiated_by VARCHAR(20) NOT NULL,
    initiated_by_user_id INTEGER,

    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    approved_at TIMESTAMPTZ,
    approved_by_user_id INTEGER,

    rejected_at TIMESTAMPTZ,
    rejected_by_user_id INTEGER,
    rejection_reason TEXT,

    cancelled_at TIMESTAMPTZ,
    cancelled_by_user_id INTEGER,
    cancellation_reason TEXT,

    received_at TIMESTAMPTZ,
    inspection_started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    customer_notes TEXT,
    internal_notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_returns_org_return_number
        UNIQUE (organization_id, return_number),

    CONSTRAINT uq_returns_org_return_id
        UNIQUE (organization_id, return_id),

    CONSTRAINT fk_returns_organization
        FOREIGN KEY (organization_id)
        REFERENCES public.organizations (organization_id),

    CONSTRAINT fk_returns_sales_order
        FOREIGN KEY (organization_id, sales_order_id)
        REFERENCES public.sales_orders (organization_id, sales_order_id),

    CONSTRAINT fk_returns_customer
        FOREIGN KEY (organization_id, customer_id)
        REFERENCES public.customers (organization_id, customer_id),

    CONSTRAINT fk_returns_status
        FOREIGN KEY (return_status_id)
        REFERENCES returns.return_statuses (return_status_id),

    CONSTRAINT fk_returns_initiated_by_user
        FOREIGN KEY (organization_id, initiated_by_user_id)
        REFERENCES public.organization_users (organization_id, user_id),

    CONSTRAINT fk_returns_approved_by_user
        FOREIGN KEY (organization_id, approved_by_user_id)
        REFERENCES public.organization_users (organization_id, user_id),

    CONSTRAINT fk_returns_rejected_by_user
        FOREIGN KEY (organization_id, rejected_by_user_id)
        REFERENCES public.organization_users (organization_id, user_id),

    CONSTRAINT fk_returns_cancelled_by_user
        FOREIGN KEY (organization_id, cancelled_by_user_id)
        REFERENCES public.organization_users (organization_id, user_id),

    CONSTRAINT chk_returns_return_number_not_blank
        CHECK (btrim(return_number) <> ''),

    CONSTRAINT chk_returns_initiated_by
        CHECK (
            initiated_by IN (
                'customer',
                'employee',
                'manager',
                'system'
            )
        ),

    CONSTRAINT chk_returns_initiator_user
        CHECK (
            (initiated_by IN ('employee', 'manager')
                AND initiated_by_user_id IS NOT NULL)
            OR
            (initiated_by IN ('customer', 'system')
                AND initiated_by_user_id IS NULL)
        )
);


------------------------------------------------------------------------
--------------------table returns.return_statuses
------------------------------------------------------------------------
CREATE TABLE returns.return_statuses (
    return_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    status_code VARCHAR(30) NOT NULL,
    status_name VARCHAR(50) NOT NULL,

    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_return_statuses_code
        UNIQUE (status_code),

    CONSTRAINT chk_return_statuses_code_not_blank
        CHECK (btrim(status_code) <> ''),

    CONSTRAINT chk_return_statuses_name_not_blank
        CHECK (btrim(status_name) <> ''),

    CONSTRAINT chk_return_statuses_sort_order
        CHECK (sort_order > 0)
);